# Generated by Django 5.2.7 on 2025-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideo',
            name='cluster_plot',
            field=models.ImageField(blank=True, null=True, upload_to='cluster_plots/'),
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='status_message',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
